MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0230s_gelu
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 8, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
    # SSM_INIT: "v2"
    SSM_ACT_LAYER: "gelu"
