MODEL:
  TYPE: vssm
  NAME: vssm1_base_0229
  DROP_PATH_RATE: 0.6
  VSSM:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 15, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v3noz"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"

# 89.0 + 15.2 + 118min/e + 48G
