MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0315
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96 # 128
    DEPTHS: [2, 2, 5, 2] # [ 2, 2, 15, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 2.0
    SSM_CONV: -1
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v4"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v2"
    PATCHEMBED: "v1"
